### PR TITLE
textures fix

### PR DESCRIPTION
**Pull request by cloudziq**
new better version of:
 -boards01
 -conc_wall01

added:
 -conc_wall01b

renamed:
 -wood_surf01 > boards02 (also new version - wood_surf was ugly)

### CODE REVIEW

**Review by no-lex — COMMENTED** [review]
Looks good, only had one concern: that `boards01_z.png` looks so blurry it's pointless as a heightmap.
I don't think it's very representative of the texture itself (but due to the blur amount i don't think it'd be particularly obnoxious either, just wasteful)

**Comment by cloudziq** [comment]
its added to make these boards appear not so flat only

**Comment by no-lex** [comment]
Alright, i'd personally sharpen the dropoff some more, but it's not especially critical.

**Comment by cloudziq** [comment]
It's blurry currently because not looked good when this was more sharp, boards were too bumpy near gaps, and when parallaxscale was reduced then bump was barely visible.

**Review by no-lex — APPROVED** [review]
Looks good to me then.

**Comment by Dziq84** [comment]
I also finalised 'big_vent' model set - now it have consistent textures, geometry fixes and proper colliders

**Comment by cloudziq** [comment]
removed other things from this PR, laeaving only original texture changes

**Pull request merged**
