### PR TITLE
set of chains

### PR DESCRIPTION
**Pull request by cloudziq**
- 8 mapmodels in total (2 variants: clean and rusty, each have 4 lenghts)
- lengths: 4, 8, 16 and 32 (chain eyelet)
- one level of LOD for each

### CODE REVIEW

**Comment by qreeves** [comment]
Rusted chains are usually duller all over due to weathering, so I think they should look less glossy.

**Comment by cloudziq** [comment]
I left a bit of gloss on the remains of the paint only, but yeah I changed now by your suggestion
With commit below, I darkened rusty diffuse, and make paint 'islands' less visible
also reduced specular drastically (by like 65%)

**Comment by qreeves** [comment]
I think you only really needed to remove the specular entirely. I mean, it's a decent variation anyway, but my point was that even paint looks dull after being weathered. Yes, I might have too much experience with chains in real life.

**Comment by cloudziq** [comment]
yeah, scrap this.   Spec removed, make diffuse a bit brighter instead by 15%

**Comment by qreeves** [comment]
Sounds good, least it can be coloured with attributes still then as well 👍

**Pull request merged**
