### PR TITLE
textures upgrades

### PR DESCRIPTION
**Pull request by cloudziq**
added one new texture - old_airbricks
tweaked a few - brickwall 1 and 2, panels, walls, metal_base
all changed textures are 1024x1024 png's and optimised
one ugly wood texture is removed - I guess I forgot to do it last time, in previous commit I added a proper replacement

### CODE REVIEW

**Comment by acerspyro** [comment]
The colourmap for your texture seems to have a lot of RGB grain/noise.

Would it be possible to smooth it out?

**Comment by cloudziq** [comment]
not sure if its necessary since this is one method to visually add micro details and also textures are smoothed a bit in game so nothing of that is visible, even on vscale 8

**Comment by acerspyro** [comment]
As per your picture, it seems to be quite visible in-game, looks like an oil spill in-between the bricks.

**Comment by cloudziq** [comment]
.. fixed this RGB noise, especially on mortar, also heightmap is smoothed

**Comment by qreeves** [comment]
Is `metal_base01.png` just a single flat colour? Seems a bit of a waste to have a 512px file with a single colour in it. Is there a way to use `textures/blank` or something instead?

**Comment by cloudziq** [comment]
umm it is not a just blank color if you look closely ;p  I will see if other texture can fit from currently included ones

**Comment by qreeves** [comment]
Alright, if it has some variation to it I just can't see that's fine though.

**Comment by cloudziq** [comment]
changed this a bit to have more variation in color

**Comment by cloudziq** [comment]
ummm but I not updated that last change :O, waited for input if it's ok or not ;p  I should ask and not just give an image of last change - my fault

**Pull request merged**
